name: Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        env: [dev, staging, prod]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          VERSION=$(jq -r '.api.tag' envs/${{matrix.env}}.json)
          echo "Pretending to deploy ${{ matrix.env }} at version $VERSION (if it changed)"
