name: Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        env: [dev, staging, prod]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          echo "Deploy ${{ matrix.env }}"
